#da second
import time
his_her_name = input("pls enter name:")
print("Hello ", his_her_name ,".I am Python the second, heir to Python the frist.")
time.sleep(2)
print("I see, he was pretty mean. However my only goal is to make your Python experience feel even better!")
time.sleep(2)
print("But frist , i'm gonna need some background info:")
time.sleep(2)
day = input("Since i'm not equipped with knowning the day of the week , i'm gonna need your user input of the day of the week:")
date =input("Oh yes , and the date(eg:6th):")
month = input("And the month:")
year =input("And maybe what year were in:")
print("Processing...")
time.sleep(2)
print("Complete!Now let's get onto some personals!")
age = input("How old are you?:")
friends = input("And just for saftely ,your friend(s) names:")
song = input("How about your fav song!:")
artist_of_song = input("And who wrote it!:")
hobbies = input("You can't forget the hobbies(Hope one of them is python!):")
carrer = input("And finnaly.... your career plans(why not):")
print("Processing...")
time.sleep(3)
print("Complete!Now let's see if i've got this right:")
time.sleep(3)
print("You are ", his_her_name , " living on the day " , day , " the " , date , " in the month " , month , " of the year " , year , ".")
time.sleep(2)
print("You have orbited the sun ", age , " times,with your friend(s) " , friends , " .")
time.sleep(2)
print("Your fav song is ", song , "made by " , artist_of_song , ".")
time.sleep(2)
print("Your current hobbies is ", hobbies , " but your future hobbies is " , carrer , ".")
time.sleep(1)
print("Whew, that was a woozy!I hope I got it all right, but for now I need a well deserved meal. Now get over here you little rabbit....")
time.sleep(3)
print("I REQUIRE MY DINNER!!!!   (No actual rabbits were harmed in the making of this program(Wait, am I a program.....))")